### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gellings** [superjax/ocam_ros#1]
withrobot_camera.hpp:27:21: fatal error: libv4l2.h: No such file or directory

**Comment by gellings** [comment]
I'm sure I can figure out how to solve this but since I'm using your repo I thought I should give some feedback.

**Comment by gellings** [comment]
```bash
sudo apt-get install libudev-dev libv4l-dev
```
fixed it for me. Perhaps just add it to the readme.  Thanks!

**Comment by gellings** [comment]
The readme also says 
```
rosrun ocam_ros ocam_ros_node
```
but I think it should be 
```
rosrun ocam_ros ocam_ros
```

**Comment by jerelbn** [comment]
I changed the run command to match the readme as `rosrun ocam_ros ocam_ros_node`

**Comment by jerelbn** [comment]
I also added `sudo apt install libudev-dev libv4l-dev` to the readme, so I'm calling this fixed.
