### ISSUE TITLE
Which Ocam

### ISSUE THREAD

**Issue by mrsp** [superjax/ocam_ros#4]
Hello 

Which ocam does this driver support? oCam-1MGN-U (mono),  oCam-1CGN-U  (rgb) or both? 

Thanks in advance!

**Comment by superjax** [comment]
I only have the RGB version - so I can't say if the 1MGN-U works.  However, their drivers are very similar between the two and it might just work, and if not, it should be a relatively small change.

I wrote this by basically wrapping ROS around their [OpenCV example](https://github.com/withrobot/oCam/tree/master/Examples/opencv-basic_1MGN), which was written for the MGN.  Which camera are you trying to use?

**Comment by mrsp** [comment]
I am considering to buy a few (since they are cheap for global shutter cameras)  for robotic applications in my lab e.g. visual odometry. 

Nevertheless, there exist some complaints about the "official" ROS driver http://withrobot.com/en/camera/ocam-1cgn-u/?ckattempt=1 i.e. frame loss, time out etc. have you noticed anything with your oCam? 

Furthermore, can you get ~160fps at 320x240?

Thanks again

**Comment by superjax** [comment]
I just tested and cleaned the node up a bit.  I am getting _pretty close_ to the full 160 fps at 320x240

![image](https://user-images.githubusercontent.com/7344014/40685423-7806de36-6351-11e8-9d06-442ee07d2a0c.png)

I think that is primarily the auto exposure calculations keeping that down (CPU usage is a little higher than I would like), I would have to spend more time to figure out why I'm a little under 160.

However, at 640x480, I get the full 80 Hz

![image](https://user-images.githubusercontent.com/7344014/40685562-d3d41440-6351-11e8-8f29-8574f953590a.png)

**Comment by mrsp** [comment]
Ok thanks for the info!

In general are you satisfied with this particular camera?

**Comment by superjax** [comment]
Yeah.. for the price and size it's hard to beat,

I really wish I could trigger the camera, or get a hardware strobe for the images so I could accurately time them, but for a USB camera it's become the go-to in my research lab.

**Comment by superjax** [comment]
For more precise stuff (like visual-inertial stuff) I typically use more expensive traditional machine vision cameras, because of the hardware trigger and/or strobe.  This is a cheap camera that I've used to prototype an idea, or class projects or something.  I've found that hardware synchronization is pretty important for precision work.

**Comment by mrsp** [comment]
Yeah my experience totally agrees with what you just said!

Thanks again for the info. 

Consider this closed :)
