### ISSUE TITLE
USB 2.0 may be crashing

### ISSUE THREAD

**Issue by jerelbn** [superjax/ocam_ros#5]

**Comment by superjax** [comment]
??

**Comment by jerelbn** [comment]
Sorry, I left out the description. Dallin says that the oCam ROS node was crashing on him, while using USB 2.0. I've been using USB 3.0 with no issues, so this is just something to look into.

**Comment by superjax** [comment]
hmmm.  okay.  Thanks.

I probably won't have time to look at it in the near future.  But thanks for making a note

**Comment by superjax** [comment]
I've been using USB 2.0 with no problems for a while now, and haven't had this issue. I'm going to close this for now.
